### ISSUE TITLE
Remove docker pull output from linuxbox_docker_run reported output

### ISSUE THREAD

**Issue by mloughran** [numtide/terraform-provider-linuxbox#11]
The linuxbox_docker_run reports stderr and stdout from its previous execution in the `terraform plan` output. This includes the docker pull output.

I have never found this useful, and it makes the output lengthy and therefore hard to review. Is there an argument for removing stderr & stdout reporting completely, or at least avoiding including the output of `docker pull` which is verbose and usually uninteresting.

Example problematic output

      ~ stderr       = <<~EOT
            Unable to find image 'eu.gcr.io/<snip>:95afb4fc' locally
            95afb4fc: Pulling from <snip>
            31dd5ebca5ef: Already exists
            3ed641c4ae98: Already exists
            bcd57146431e: Already exists
            ac34a4d7c330: Already exists
            3b0a7e6f20fb: Already exists
            9b92c6962c60: Already exists
            e437cfe9dffe: Already exists
            06d567a064d2: Already exists
            a1593c54eb5e: Already exists
            4e4afc142b23: Already exists
            20b52abbd030: Already exists
            9d8d868005db: Already exists
            51246e6cbf67: Already exists
            4caa1f91317c: Pulling fs layer
            2299274fc940: Pulling fs layer
            bd2a51264442: Pulling fs layer
            bd2a51264442: Download complete
            4caa1f91317c: Verifying Checksum
            4caa1f91317c: Download complete
            2299274fc940: Verifying Checksum
            2299274fc940: Download complete
            4caa1f91317c: Pull complete
            2299274fc940: Pull complete
            bd2a51264442: Pull complete
            Digest: sha256:4f98f092430298cfb5cad6ddcd2137b84bc547bf6b7072fca87f37d5de11f369
            Status: Downloaded newer image for eu.gcr.io/<snip>:95afb4fc

**Comment by draganm** [comment]
it is solved in the latest release
