### ISSUE TITLE
[question] specify ssh port

### ISSUE THREAD

**Issue by rucciva** [numtide/terraform-provider-linuxbox#18]
hi, i noticed [this line](https://github.com/numtide/terraform-provider-linuxbox/blob/master/sshsession/pool.go#L109). So is ssh port hardcoded? or is there any mechanism  to specify port other than 22 ?

thanks

**Comment by draganm** [comment]
At the moment the port is hard coded. If you have a really good case for having it as a parameter, might consider adding it. What do you need it for? What scenario are we talking about? Would you prefer setting the port on the provider (forcing all resources using that port) or per resource?

**Comment by rucciva** [comment]
hi, i ended up creating my own provider for my case, thanks.
